development:
  adapter: postgresql
  database: christinetran
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: christinetran
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: christinetran
  pool: 5
  timeout: 5000
